name: FEC Project Check

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Complete successfully
        run: |
          echo "FEC Project workflow completed successfully."
